### ISSUE TITLE
Possible to validate/modify casing of component name?

### ISSUE THREAD

**Issue by zkwsk** [gventuri/create-react-component#8]
Thanks for creating this great little utility.

I realize this is more of a general enquiry or maybe even a change request than an issue, but I would like to know if there is currently a way to modify the casing of my component name?

For example I would like to call the component file itself `MyComponent.component` but inside my component I want to initialize it to always have a css-class `my-component` (so lower- and hyphen case). Is there any way to achieve this with the current way of parsing the templates?

**Comment by gventuri** [comment]
Hi @zkwsk, thank you for sharing your feedback. I have implemented the feature you asked and released a new version 1.4.0.

First of all, you need to update the package globally. Then to implement what you suggested, follow this steps:

You can change the case type used in the file name. To do that, you should add a comment at the beginning of the file you want to edit, like in the example:

```
/**
 * @caseType kebabCase
 */
```

In the previous example, the file will be saved in kebabCase. You can choose from one of the following: kababCase, snakeCase, CamelCase. By default, if you don't provide any value, it will be used PascalCase.

At this point, as your file name has been changed, you might need to change the name used in the dependencies. In order to do that, you need to edit slightly the file where you are including the dependency. For example, if you want to include a css file in your project and you want that file to be saved with kebab case, you need to edit your file from

```
import styles from './$name.module.scss';
```

to

```
import styles from './$(name, {"caseType": "kebabCase"}).module.scss';
```

As you can see in the example about, you are passing a JSON object as second parameter of a function. In the JSON object, you provide the caseType to kebabCase.

Just let me know if it works fine!
